### ISSUE TITLE
xorg-kit question

### ISSUE THREAD

**Issue by CharlesGueunet** [funtoo/meta-repo#9]
Hello,

I have a question concerning the Xorg-kit.
The [git](https://github.com/funtoo/xorg-kit/tree/1.20-prime) seems to indicate that there is now two branches:
* 1.17-prime
* 1.20-prime
But the [kit-sha1.json](https://github.com/funtoo/meta-repo/blob/master/metadata/kit-sha1.json) file on this meta-repo contains:
```   
 "xorg-kit": {
        "1.17-prime": "56d4010dc0107e09799c15cf5fc067a696a8bfbf",
        "1.19-prime": "f16be27ba039e74d3afc0aaba1ca6833795c6fcb"
    }
```

As I was on the 1.20-release branch, I actually have some trouble updating. Is this a bug from the meta-repo ?

Thanks for your help,
Charles

**Comment by vollia** [comment]
look like it has been fixed now, thanks.
